### ISSUE TITLE
Sigma breaks all Kopernicus planet packs in 1.12.3 (resolved?)

### ISSUE THREAD

**Issue by ratemisia** [Sigma88/Sigma-Dimensions#100]
I hope the title explains my issue in short - when using Sigma Dimensions in conjunction with any Kopernicus planet pack I have yet tried, Module Manager throws these errors during the loading process:
![image](https://user-images.githubusercontent.com/103651498/163406063-f570a7b3-55ef-427a-b07d-0c45b7f0cdb4.png)

And spams exceptions into KSP.log (which I would add here, but the file size has made uploading it difficult - will do so when I figure that out,)

with Kopernicus stating this error once main menu opens:
![image](https://user-images.githubusercontent.com/103651498/163406502-1baac629-245b-45ed-a7ef-1214620d59ec.png)

**Comment by ratemisia** [comment]
Pinging @R-T-B here, on account of Kopernicus being heavily involved in this error - perhaps something on Kopernicus's side rather than SigmaDimensions, although I highly doubt it on account of the error reliably disappearing on SigmaDimensions deletion.

Log from an install with Dimensions, some visual mods, and planet packs - stripped down from my usual install.
[KSP.log](https://github.com/Sigma88/Sigma-Dimensions/files/8490080/KSP.log)

Upon reviewing the errors, I've found that it may even be related to Environmental Visual Enhancements, so I'll try an install without to see if that works fine.
(Edit: No change. Still got an identical error both during loading and in main menu.)

**Comment by R-T-B** [comment]
Interesting.  I take it 1.12.3 works fine?

That is odd.  I'll poke around a bit when I get home from work...

**Comment by ratemisia** [comment]
I haven't tested it in 1.12.3, actually - I may be able to do that when I get home, but I have no reason so far to suspect that it would work differently.

**Comment by R-T-B** [comment]
> I haven't tested it in 1.12.3, actually - I may be able to do that when I get home, but I have no reason so far to suspect that it would work differently.

Well I for one am using it in 1.12.3 but with the vanilla system.  hmm ....

**Comment by ratemisia** [comment]
Can confirm - with the same mod combination in 1.12.3, I have had the same error.

**Comment by R-T-B** [comment]
Got home, had a chance to look at your logs.  Here's the first few things I notice:

1.)  You have two module managers present, as indicated here:

[LOG 10:39:39.363] [ModuleManager] version 4.1.4.0 at D:\Kerbal Space Program Saves\Test\TestInstall\GameData\ModuleManager.4.1.4.dll won the election against
Version 4.1.4.0 D:\Kerbal Space Program Saves\Test\TestInstall\GameData\ModuleManager.4.2.1.dll 

Please use only one module manager, preferably the newest one.

That could be the issue, but I suspect more is going on.  You have a lot of additional mods that make this a hard case to unwind.  I just tested with only Kopernicus (latest stable release), SigmaDimensions, and a planet pack (JNSQ in my case) and it seemingly is working.  So something else is interfering in your modstack.  You just need to determine what.  Look for things that may be out of date or incorrectly installed in some fashion.  Some suspects might be Distant Object Enhancement (it's throwing errors, unsure if because of something else or if out of date), and EnvironmentalVisualEnhancements.  Could be other stuff too, just some ideas.

Also, KSP-AVC is spazzing out.  I'm not sure it's even supported anymore.  It's just an update script.  I'd remove its folder from gamedata.  Maybe ZeroMiniAVC as well?

**Comment by ratemisia** [comment]
Will see if those fixes work and get back to this.

**Comment by ratemisia** [comment]
Update: went back through my files, deleting duplicates and updating to the latest versions, and noticed that Dimensions was incorrectly installed. Won't close the issue yet - want to confirm that my fixes have actually worked before doing so - but I will take this opportunity to state to others that may be having a similar problem:
**ALWAYS** double-check your installation to make sure you have done it correctly and with a compatible version of the mod, and look for mistakes **IMMEDIATELY** when anything goes wrong! Don't be me and start an issue when your install is borked and all your mods are out of date.
