### ISSUE TITLE
Geostationary Orbit

### ISSUE THREAD

**Issue by HooHungLow** [Sigma88/Sigma-Dimensions#58]
How do I calculate a Geostationary orbit for Kerbin at 2x stock?

Also, I am having an issue calculating the new DeltaV needed for LKO. I've been guesstimating but maybe you can help me. I have everything (resize, rescale, day length) set to 2x stock, but I changed the atmosphere setting to 1.5x. 

Any help is appreciated. 

Thanks!

**Comment by Ketters** [comment]
Geostationary orbit altitude is just some algebra and physics and using the formula for orbital altitude r = (mu/(omega^2))^(1/3), where mu is Kerbin's gravitational constant (mu = G*M, and this value is 3.5315984×10^(12) m3/s2 for Kerbin), and omega is the orbiting object's angular velocity.  You want the angular velocity to be 2 times pi divided by the length of a Kerbin day in the rescale in seconds.

The resize config file will have a setting called `dayLengthMultiplier`.  Look for that, and multiply it by 21600 to get 2x Kerbin's day length in seconds.

The geostationary orbital radius will be ((mu value for Kerbin)/([2*pi/(length of Kerbin day in your config in seconds)]^2))^(1/3).

Formula in a nicer form given [here](http://www.texpaste.com/n/cmdut8m6).

For finding the dv to get into orbit, that's not exactly an easy thing since there are a lot of variables that go into affecting the delta v needed to reach orbit, and they can vary between rockets and launch profiles.  Best you can do is an approximation based on guessing an ideal launch profile, knowledge of the atmospheric profile of Kerbin (possibly stock Kerbin with a 1.5x scale height factor), and factoring in gravity losses and steering losses.  You'd likely have to do integrals over the launch trajectory as well.  Unless you're good at calculus and have some free time, might be better off just guessing it.

**Comment by Sigma88** [comment]
>where mu is Kerbin's gravitational constant (mu = G*M, and this value is 3.5315984×10^(12) m3/s2 for Kerbin

looking at [the code](https://github.com/Kopernicus/kittopia-dumps/blob/master/Configs/Kerbin.cfg), kerbin's grav parameter is 3531600000000

**Comment by HooHungLow** [comment]
Thanks for the info, I am showing the 2x Kerbin day length at 43057 seconds. I appreciate you setting up that formula for me but I have to be honest I am not nearly as good of a mathematician. Maybe I can get you the data and you can help me with solving it?

**Comment by Ketters** [comment]
> looking at the code, kerbin's grav parameter is 3531600000000
Ahh.  I pulled my number off of the KSP wiki.

> Maybe I can get you the data and you can help me with solving it?
Sure thing.  Don't mind doing math.

I found the geostationary altitude around 2x Kerbin to be about 5,494.1 km.  I used Sigma's value for the gravitational parameter.  I recommend using MechJeb or Kerbal Engineer if you don't already so you can have real-time orbital period data.

**Comment by HooHungLow** [comment]
Thanks @Ketters , I am using KER and Mechjeb, It's strange because just eyeballing it last night I was having to get up to about 7,525-ish Km in order to bring my orbital period up to 11hrs 57-58mins.

**Comment by HooHungLow** [comment]
Exact orbital period is 11hrs 57ms 37s.

**Comment by Ketters** [comment]
Hmm.  That's odd since I used your number for sidereal orbital period and @Sigma88's mu parameter.  I am confident that I used the correct formula to find the geostationary orbital radius.

However, I did forget to subtract Kerbin's radius from my answer.  That still would not give the correct answer.  I feel that I incorrectly assumed that mu doesn't change with radius since it's G*M.  G would be constant for Kerbin with a surface gravitational acceleration of 1g, but the mass must change, and I assumed constant mass by proxy of assuming constant mu.

I calculated a new mu value and used it to find a new geostationary orbit.  I do get 7,518.4 km, which matches very close to the altitudes you had to get to for geostationary orbits.

I'm confident that 7,518.4 km is the correct answer or very close to it, so getting close to that will get you geostationary orbits.

Glad you reported about that since I would have no clue about my bad assumption of mu values otherwise.

**Comment by HooHungLow** [comment]
@Ketters Thanks so much. I appreciate your help with this. I will launch into that orbit and let you know if it matches, but I think you are right on.

**Comment by Sigma88** [comment]
@Ketters G is big G (the gravitational constant), which is 6.67408e-11

and mu will definitely change with a resized planet, since the mass scales with the square of the resize (which means mu does the same)

**Comment by Sigma88** [comment]
my suggestion would be to install kittopia tech and write down Kerbin's rotation period and gravParameter

you can calculate the SMA of the geostationary orbit using those values:

period = 2 * pi * sqrt( SMA ^ 3 / gravParameter)

**Comment by Sigma88** [comment]
which becomes:
SMA = (period ^ 2 * gravParameter / 4 pi^2) ^ (1/3)

**Comment by Ketters** [comment]
@Sigma88 Figures it changes with the square of radius.  I calculated mu from taking F = (mu)*m/(r^2), setting m = 1kg and F = 9.8 N (force from gravity on a 1kg object on the surface of a planet with 1g surface gravity).  Then I solved for mu and got the number I did.  That also means mu = 9.8r^2, With 9.8 having units of meters/(second^2) and mu is the gravParameter.

**Comment by Sigma88** [comment]
for future reference, KSP uses:

G = 6.67408e-11
g = 9.80665
